# Generated by Django 4.1.6 on 2023-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=32)),
                ('tasks', models.JSONField(blank=True)),
                ('complete', models.JSONField(blank=True)),
            ],
        ),
    ]
