# Generated by Django 4.1.6 on 2023-02-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_alter_userdata_complete_alter_userdata_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='pwd',
        ),
    ]
